### ISSUE TITLE
CREAR LAMBDA PARA OBTENER TIPOS DE PRODUCTOS

### ISSUE THREAD

**Issue by Julay14** [USMP2024/Taller-de-proyectos#24]
**Historia de Usuario**
#20 Menú de inicio

**Comment by JendyBaldoceda13** [comment]
H1-006_LAM-001 LAMBDA-OBTENER TIPO PRODUCTOS

1. Deberia devolver tipos de productos si la consulta es exitosa.

- Correcto se otorga 33.3% del total

2. Deberia devolver un error 500 si hay un error al ejecutar la consulta SQL.

- Correcto se otorga 33.3% del total

3. Deberia cerrar la conexión a la base de datos después de ejecutar la consulta.

- Correcto se otorga 33.3% del total

Porcentaje total de pruebas realizadas:100%

Conclusión : La LAMBDA-OBTENER TIPO PRODUCTOS pasará a hecho ya que logró pasar todas las pruebas satisfactoriamente.


![Image](https://github.com/USMP2024/Taller-de-proyectos/assets/162405237/767a15fe-18d3-4883-a9f3-c79cc1620588)


![Image](https://github.com/USMP2024/Taller-de-proyectos/assets/162405237/30a7d3b7-927c-41ca-a38e-69cd5246ff6c)

FIRMADO POR LA QA JENDY BALDOCEDA
