### ISSUE TITLE
CREAR LAMBDA PARA MOSTRAR TENDENCIAS

### ISSUE THREAD

**Issue by Julay14** [USMP2024/Taller-de-proyectos#25]
**Historia de Usuario**
#20 Menú de inicio

**Comment by JendyBaldoceda13** [comment]
H1-006_LAM-002 LAMBDA-MOSTRAR TENDENCIAS

1. Deberia devolver productos ordenados por contador de visitas si la consulta es exitosa.

- Correcto se otorga 33.3% del total

2. Deberia devolver un error 500 si hay un error al ejecutar la consulta.

- Correcto se otorga 33.3% del total

3. Deberia cerrar la conexión a la base de datos después de ejecutar la consulta.

- Correcto se otorga 33.3% del total

Porcentaje total de pruebas realizadas:100%

Conclusión : La LAMBDA-MOSTRAR TENDENCIAS pasará a hecho ya que logró pasar todas las pruebas satisfactoriamente.



![Image](https://github.com/USMP2024/Taller-de-proyectos/assets/162405237/b6803388-7508-4823-bb49-71e973b69e7c)



![Image](https://github.com/USMP2024/Taller-de-proyectos/assets/162405237/612ad2d1-53ae-4545-afa1-133ba8613e0b)

FIRMADO POR LA QA JENDY BALDOCEDA
