### ISSUE TITLE
CREAR LAMBDA PARA MOSTRAR COLECCIONES NUEVAS

### ISSUE THREAD

**Issue by Julay14** [USMP2024/Taller-de-proyectos#26]
**Historia de Usuario**
#20 Menú de inicio

**Comment by JendyBaldoceda13** [comment]
H1-006_LAM-004 LAMBDA-MOSTRAR COLECCIONES NUEVAS

1. Deberia devolver colecciones si la consulta es exitosa.

- Correcto se otorga 33.3% del total

2. Deberia devolver un error 500 si hay un error al ejecutar la consulta.

- Correcto se otorga 33.3% del total

3. Deberia cerrar la conexión a la base de datos después de ejecutar la consulta.

- Correcto se otorga 33.3% del total

Porcentaje total de pruebas realizadas:100%

Conclusión : La LAMBDA-MOSTRAR COLECCIONES NUEVAS pasará a hecho ya que logró pasar todas las pruebas satisfactoriamente.



![Image](https://github.com/USMP2024/Taller-de-proyectos/assets/162405237/c3d5f46e-ad46-42c1-b561-ecef5df9257e)



![Image](https://github.com/USMP2024/Taller-de-proyectos/assets/162405237/7e7873c9-470c-4879-ae1f-693b8a541688)

FIRMADO POR LA QA JENDY BALDOCEDA
