### ISSUE TITLE
CREAR LAMBDA SUBIR ARCHIVOS

### ISSUE THREAD

**Issue by Julay14** [USMP2024/Taller-de-proyectos#31]
**Historia de Usuario**
#3 Subir archivos

**Comment by JendyBaldoceda13** [comment]
H2-001_LAM-001 LAMBDA-SUBIR-ARCHIVO

1. Debería cargar un archivo en s3 correctamente.

- Correcto se otorga 0% del total

Porcentaje total de pruebas realizadas: 0%

Conclusión : La LAMBDA-SUBIR-ARCHIVO volverá  a En Progreso  ya que no logró pasar todas las pruebas satisfactoriamente.



![Image](https://github.com/USMP2024/Taller-de-proyectos/assets/162405237/f97a1096-8ece-4256-b79f-84daefb68c11)



![Image](https://github.com/USMP2024/Taller-de-proyectos/assets/162405237/249c90bc-778c-4db8-a0cf-f7e412b41ea3)

FIRMADO POR LA QA JENDY BALDOCEDA
