### ISSUE TITLE
Crear lambda para editar usuarios

### ISSUE THREAD

**Issue by Julay14** [USMP2024/Taller-de-proyectos#42]
**Historia de Usuario**
#16 Administrador general

**Comment by JendyBaldoceda13** [comment]
H6-001_LAM-001 LAMBDA-EDITAR-USUARIO

1. Debe retornar un 200 si el usuario se actualiza correctamente

- Correcto se otorga 50% del total

2. Debe retornar un 500 si no se proporciona el ID del usuario

- Correcto se otorga 50% del total

Porcentaje total de pruebas realizadas:100%

Conclusión : La LAMBDA-EDITAR-USUARIO pasará a hecho ya que logró pasar todas las pruebas satisfactoriamente.


![Image](https://github.com/USMP2024/Taller-de-proyectos/assets/162405237/ee85f6ef-9e81-4611-8fd9-cbd45fa5b817)



![Image](https://github.com/USMP2024/Taller-de-proyectos/assets/162405237/7ac4d5ca-2e51-4467-8036-d3ae3d580662)



FIRMADO POR LA QA JENDY BALDOCEDA.
