### ISSUE TITLE
Crear lambda para eliminar usuarios

### ISSUE THREAD

**Issue by Julay14** [USMP2024/Taller-de-proyectos#43]
**Historia de Usuario**
#16 Administrador general

**Comment by JendyBaldoceda13** [comment]
H6-001_LAM-002 LAMBDA-ELIMINAR-USUARIOS

1. Debería eliminar un usuario existente 

- Correcto se otorga 25% del total 

2. Debería manejar el caso en que el usuario no existe 

- Correcto se otorga 25% del total 

3. Debería manejar el caso en que idusuario sea nulo 

- Correcto se otorga 25% del total 

4. Debería manejar el caso en que idusuario esté vacío

- Correcto se otorga 25% del total 

Porcentaje total de pruebas realizadas:  100%  

Conclusión : La  LAMBDA-ELIMINAR-USUARIOS pasára a hecho ya que logró pasar todas las pruebas satisfactoriamente.


![Image](https://github.com/USMP2024/Taller-de-proyectos/assets/162405237/5954c341-ae9a-44e2-a7b1-1d066784f72d)



![Image](https://github.com/USMP2024/Taller-de-proyectos/assets/162405237/b004501b-c6d7-4607-a08c-5daba5f306be)

FIRMADO POR LA QA JENDY BALDOCEDA.
