### ISSUE TITLE
Crear lambda-listar-clientes

### ISSUE THREAD

**Issue by Julay14** [USMP2024/Taller-de-proyectos#86]
**Historias de Usuario**
#16  Administrador general

**Comment by JendyBaldoceda13** [comment]
H6-001_LAM-003 LAMBDA-LISTAR CLIENTES

1. Deberia devolver la lista de clientes si la consulta es exitosa

- Correcto se otorga 25% del total 

2. Deberia devolver un mensaje de error si la consulta SQL falla

- Correcto se otorga 25% del total 

3. Deberia devolver un mensaje indicando que no hay clientes si no hay resultados

- Correcto se otorga 25% del total 

4. Debería cerrar la conexión a la base de datos después de ejecutar la consulta

- Correcto se otorga 25% del total 

Porcentaje total de pruebas realizadas:100%

Conclusión : La LAMBDA-LISTAR CLIENTES pasará a hecho ya que logró pasar todas las pruebas satisfactoriamente.




![Image](https://github.com/USMP2024/Taller-de-proyectos/assets/162405237/d6d78737-c492-461d-a1d8-9361d7798514)



![Image](https://github.com/USMP2024/Taller-de-proyectos/assets/162405237/be508bf7-e6a0-4722-8a3e-4ad759d5a425)

FIRMADO POR LA QA JENDY BALDOCEDA.
